## Libraries Setup

In [1]:
import pandas as pd 
import numpy as np

## cvs Files import

In [7]:
df_amazon_jan24_raw = pd.read_csv('inbound_reports/amazon_jan24_raw.csv')
df_amazon_jan24_raw.head()

,ArtistName,LabelName,TrackTitle,ISRC,AlbumTitle,UPC,CountryCode,Service_Tier,PlayCount,Royalty,CurrencyCode,Period_Start,Period_End,ASIN
0,Heather Campbell,Thompson-Kennedy Entertainment,Ergonomic Mobile Matrices,SEPCQ2078164,Incentivize Out-Of-The-Box Users,3615792141804,CO,Prime,2,0.00,USD,2024-01-01,2024-01-31,B0Z3ZJ1TNM
1,Claire Nelson,Merge Records,Distributed Human-Resource Encryption (Remix),US0RP2132653,Whiteboard End-To-End Networks - Single,7036509867998,FR,Prime,117,0.25,EUR,2024-01-01,2024-01-31,B0GRPWSETW
2,Carlos Mcneil,Red Bull Records,Balanced Asynchronous Circuit (Remix),USU1B1999467,Disintermediate B2C Networks,7033698387288,JP,Unlimited,54,19.50,JPY,2024-01-01,2024-01-31,B0930A65T4
3,Cole and the Foods,Underground Leblanc-Smith Recordings,Exclusive Even-Keeled Service-Desk,USYI42092764,Monetize Granular E-Services,846056613526,PL,Unlimited,2,0.01,USD,2024-01-01,2024-01-31,B0DWLW5S0Z
4,Shawn Hoffman DVM,"Price, Bowers and Campbell Entertainment",Synchronized Modular Core,NL8482350277,Streamline Extensible Markets,6579146561035,NL,Unlimited,93,0.58,EUR,2024-01-01,2024-01-31,B00HDF9OUV

In [6]:
df_amazon_feb24_raw = pd.read_csv('inbound_reports/amazon_feb24_raw.csv')
df_amazon_feb24_raw.head()

,ArtistName,LabelName,TrackTitle,ISRC,AlbumTitle,UPC,CountryCode,Service_Tier,PlayCount,Royalty,CurrencyCode,Period_Start,Period_End,ASIN
0,Heather Campbell,Thompson-Kennedy Entertainment,Ergonomic Mobile Matrices,SEPCQ2078164,Incentivize Out-Of-The-Box Users,3615792141804,CO,Unlimited,7,0.03,USD,2024-02-01,2024-02-29,B0NEBQOFGD
1,Claire Nelson,Merge Records,Distributed Human-Resource Encryption (Remix),US0RP2132653,Whiteboard End-To-End Networks - Single,7036509867998,FR,Unlimited,639,2.30,EUR,2024-02-01,2024-02-29,B0EO4NI1LB
2,Carlos Mcneil,Red Bull Records,Balanced Asynchronous Circuit (Remix),USU1B1999467,Disintermediate B2C Networks,7033698387288,JP,Unlimited,8,4.50,JPY,2024-02-01,2024-02-29,B0PDDQSGA8
3,Cole and the Foods,Underground Leblanc-Smith Recordings,Exclusive Even-Keeled Service-Desk,USYI42092764,Monetize Granular E-Services,846056613526,PL,Prime,1,0.00,USD,2024-02-01,2024-02-29,B08G93NXY3
4,Shawn Hoffman DVM,"Price, Bowers and Campbell Entertainment",Synchronized Modular Core,NL8482350277,Streamline Extensible Markets,6579146561035,NL,Prime,197,0.50,EUR,2024-02-01,2024-02-29,B0B9F2O0ER